os: linux
dist: bionic

services:
    - xvfb

language: node_js
node_js:
    - "12"
addons:
    apt:
        packages:
            - exiftran
            - libimage-exiftool-perl
            - coreutils

script:
    - chmod +x ./file-organizer.sh
    - ./file-organizer.sh dump test/data
    - npm run test-unit
    - npm run test-system
    - npm run style
