language: node_js
node_js:
    - "12"

addons:
    apt:
        packages:
            - exiftran
            - libimage-exiftool-perl
            - coreutils

before_script:
    - ./file-organizer.sh dump test/data

script:
    - npm run test
    - npm run style
