os: linux
dist: focal

language: node_js
node_js:
  - "14"

addons:
  apt:
    packages:
      - make
      - exiftran
      - libimage-exiftool-perl
      - coreutils

install:
  - make build

before_script:
  - xvfb-run ./file-organizer.sh dump test/data
  - ./src/main/main.js info test/data/canon.JPG
  - ./src/main/main.js info -k exif_timestamp test/data/canon.JPG

script:
  - make test
  - make lint
